version: 2

updates:
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "Technical Dept"
  - package-ecosystem: "maven"
    directory: "/"
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"
    labels:
      - "Technical Dept"
  - package-ecosystem: npm
    directory: "/docs"
    target-branch: "dev"
    labels:
      - "Technical Dept"
    schedule:
      interval: weekly
