version: 2

updates:
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "Technical Dept"
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "Technical Dept"
  - package-ecosystem: npm
    directory: "/digiwf-apps"
    target-branch: "dev"
    labels:
      - "Technical Dept"
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: "/digiwf-docs"
    target-branch: "dev"
    labels:
      - "Technical Dept"
    schedule:
      interval: daily
