// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DocumentCreation: typeof import('./src/components/DocumentCreation.vue')['default']
    VBtn: typeof import('vuetify/lib')['VBtn']
  }
}
