spring:
  banner:
    location: banner.txt
  application:
    name: digiwf-s3-integration-example app
  datasource:
    url: '${S3INTEGRATION_DATASOURCE_URL}'
    username: '${S3INTEGRATION_DATASOURCE_USER}'
    password: '${S3INTEGRATION_DATASOURCE_PASSWORD}'
    driver-class-name: '${S3INTEGRATION_DATASOURCE_DRIVERCLASSNAME}'
  jpa:
    database-platform: '${S3INTEGRATION_DATABASE_PLATFORM}'
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: validate
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_BOOTSTRAP_SERVER:localhost}:${KAFKA_BOOTSTRAP_SERVER_PORT:29092}
          producerProperties:
            value:
              serializer: org.springframework.kafka.support.serializer.JsonSerializer
            key:
              serializer: org.springframework.kafka.support.serializer.JsonSerializer
          consumerProperties:
            auto:
              offset:
                reset: latest
            key:
              deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
            value:
              deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
          configuration:
            security:
              protocol: ${KAFKA_SECURITY_PROTOCOL:PLAINTEXT}
      bindings:
        functionRouter-in-0:
          group: "dwf-s3-service"
          destination: dwf-s3-client-${DIGIWF_ENV}
        sendCorrelateMessage-out-0:
          destination: dwf-digiwf-engine-${DIGIWF_ENV}
        sendMessage-out-0:
          destination: dwf-digiwf-engine-${DIGIWF_ENV}
    function:
      definition: functionRouter;sendMessage;sendCorrelateMessage;sendBpmnError;sendIncident;
  kafka:
    consumer:
      properties:
        spring:
          json:
            trusted:
              packages: '*'

server:
  port: '8086'

logging:
  level:
    org:
      springframework: info
    io:
      muenchendigital: info
io:
  muenchendigital:
    digiwf:
      s3:
        bucketname: ${S3_BUCKETNAME}
        accesskey: ${S3_ACCESSKEY}
        url: ${S3_URL:http://localhost:9000}
        secretkey: ${S3_SECRETKEY}
        client:
          document-storage-url: "${DOCUMENT_STORAGE_HOST:http://localhost}:${DOCUMENT_STORAGE_PORT:8080}"
          securityEnabled: false
        proxyUrl: "${S3_PROXY_HOST:localhost}:${S3_PROXY_PORT:9000}"
        cronjob:
          cleanup:
            unused-files: 0 15 10 16 * ?
            expired-files: 0 15 10 15 * ?
        proxyEnabled: 'false'
      streaming:
        typeMappings:
          createPresignedUrl: createPresignedUrl
