spring:
  # Spring JPA
  h2.console.enabled: true
  jpa:
    hibernate:
      # always drop and create the db should be the best
      # configuration for local (development) mode. this
      # is also the default, that spring offers by convention.
      # but here explicite:
      ddl-auto: update
    # Logging for database operation
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: false
