spring:
  cloud:
    stream:
      bindings:
        functionRouter-in-0:
          group: "dwf-example-integration-local-01"
          destination: "digiwf-example-integration-local-01"
        sendMessage-out-0:
          destination: "dwf-connector-local-01"
io:
  muenchendigital:
    digiwf:
      message:
        incidentDestination: "dwf-connector-incident-local-01"
        bpmnErrorDestination: "dwf-connector-bpmnerror-local-01"
        correlateMessageDestination: "dwf-connector-local-01"
        deadLetterQueueDestination: "dwf-connector-incident-${DIGIWF_ENV}"

server:
  port: 8088
