server:
  port: '10005'
spring:
  cloud:
    function:
      definition: sendMessage;
    stream:
      bindings:
        sendMessage-out-0:
          destination: "dwf-email-${DIGIWF_ENV}"
      kafka:
        binder:
          configuration:
            security:
              protocol: ${KAFKA_SECURITY_PROTOCOL:PLAINTEXT}
          producerProperties:
            value:
              serializer: org.springframework.kafka.support.serializer.JsonSerializer
            key:
              serializer: org.springframework.kafka.support.serializer.JsonSerializer
          consumerProperties:
            auto:
              offset:
                reset: latest
            key:
              deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
            value:
              deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
          brokers: ${KAFKA_BOOTSTRAP_SERVER:localhost}:${KAFKA_BOOTSTRAP_SERVER_PORT:29092}
  kafka:
    consumer:
      properties:
        spring:
          json:
            trusted:
              packages: '*'
  mail:
    port: ${MAIL_PORT:1025}
    host: ${MAIL_HOST:localhost}
    username: ${MAIL_USERNAME:digiwf@muenchen.de}
    password: ${MAIL_PASSWORD:test}
    properties:
      mail:
        debug: false
        tls: true
        transport:
          protocol: smtp
        smtp:
          port: ${MAIL_PORT:1025}
          host: ${MAIL_HOST:localhost}
          connectiontimeout: '10000'
          timeout: '10000'
          auth: true
          ssl:
            trust: '*'
            checkserveridentity: false
          socketFactory:
            fallback: true
          starttls:
            enable: true
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
io:
  muenchendigital:
    digiwf:
      mail:
        fromAddress: ${MAIL_USERNAME:digiwf@muenchen.de}
        metrics:
          totalMailCounterName: "digiwf.email.integration.send_mail.total"
          failureCounterName: "digiwf.email.integration.send_mail.failure"
      message:
        incidentDestination: "dwf-connector-incident-${DIGIWF_ENV}"
        bpmnErrorDestination: "dwf-connector-bpmnerror-${DIGIWF_ENV}"
        correlateMessageDestination: "dwf-digiwf-engine-${DIGIWF_ENV}"
        typeMappings:
          sendMailFromEventBus: "emailMessageProcessor"
