io:
  muenchendigital:
    digiwf:
      message:
        incidentDestination: "incident"
        technicalErrorDestination: "technical-error"
        correlateMessageDestination: "correlate-message"
        startProcessDestination: "start-process"
