io:
  muenchendigital:
    digiwf:
      message:
        incidentDestination: "digiwf-message-scs-example-incident"
        technicalErrorDestination: "digiwf-message-scs-example-technical-error"
        correlateMessageDestination: "digiwf-message-scs-example-correlate-message"
        startProcessDestination: "digiwf-message-scs-example-start-process"
        typeMappings:
          digiwf-message-scs-example-incident: "onIncidentConsumer"
          digiwf-message-scs-example-technical-error: "onTechnicalErrorConsumer"
          correlatemessagev01: "correlateMessageConsumer"
          startProcessV01: "startProcessConsumer"

spring:
  cloud:
    stream:
      bindings:
        functionRouter-in-0:
          group: "digiwf-message-scs-example"
          destination: "digiwf-message-scs-example,digiwf-message-scs-example-incident,digiwf-message-scs-example-technical-error,digiwf-message-scs-example-correlate-message,digiwf-message-scs-example-start-process"
          error-handler-definition: "customErrorHandler"
        sendMessage-out-0:
          destination: "digiwf-message-scs-example"
      kafka:
        binder:
          brokers: "${KAFKA_BOOTSTRAP_SERVER:localhost}:${KAFKA_BOOTSTRAP_SERVER_PORT:29092}"
          producerProperties:
            value:
              serializer: org.springframework.kafka.support.serializer.JsonSerializer
            key:
              serializer: org.springframework.kafka.support.serializer.JsonSerializer
          consumerProperties:
            auto:
              offset:
                reset: latest
            value:
              deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
            key:
              deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
          configuration:
            security:
              protocol: "${KAFKA_SECURITY_PROTOCOL:PLAINTEXT}"
    function:
      definition: functionRouter;sendMessage;
  kafka:
    consumer:
      properties:
        spring:
          json:
            trusted:
              packages: "*"
