#spring:
#  jpa:
#    show-sql: 'true'
#    properties:
#      hibernate:
#        format_sql: 'true'
#  h2:
#    console:
#      enabled: 'true'

#security:
#  logging:
#    requests: all

spring:
  sleuth:
    web:
      enabled: false

logging:
  level:
    io.muenchendigital.digiwf.legacy.form.domain.service.FormService: WARN
    org.springframework.boot.web: DEBUG
    io.muenchendigital.digiwf.shared.configuration: DEBUG
camunda:
  bpm:
    admin-user:
      id: admin
      first-name: Admin
      last-name: Administratus
      email: ex.admin@munchen.de
      password: admin
    login:
      enabled: true
      user-id: admin
