#spring:
#  jpa:
#    show-sql: 'true'
#    properties:
#      hibernate:
#        format_sql: 'true'
#  h2:
#    console:
#      enabled: 'true'

#security:
#  logging:
#    requests: all

spring:
  sleuth:
    web:
      enabled: false

logging:
  level:
    de.muenchen.oss.digiwf.legacy.form.domain.service.FormService: WARN
    de.muenchen.oss.digiwf.shared.configuration: DEBUG
    org.springframework.boot.web: TRACE
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE

