#spring:
#  jpa:
#    show-sql: 'true'
#    properties:
#      hibernate:
#        format_sql: 'true'
#  h2:
#    console:
#      enabled: 'true'

#security:
#  logging:
#    requests: all

spring:
  sleuth:
    web:
      enabled: false

server:
  error:
    include-exception: true
    include-stacktrace: always
    whitelabel:
      enabled: true

logging:
  level:
    de.muenchen.oss.digiwf.legacy.form.domain.service.FormService: WARN
    de.muenchen.oss.digiwf.shared.configuration: INFO
    org.springframework.boot.web: INFO
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: INFO

digiwf:
  streaming:
    cocreation:
      deploy:
        # all deployments are reported back to cocreation local
        topic: 'dwf-cocreation-deploy-local-01'
