server:
  port: '${DMS_INTEGRATION_SERVER_PORT:-8080}'
spring:
  application:
    name: @project.artifactId@
  cloud:
    function:
      definition: functionRouter;sendMessage;
    stream:
      function:
        routing:
          enabled: 'true'
      bindings:
        functionRouter-in-0:
          group: "dwf-dms-service"
          destination: "dwf-dms-${DIGIWF_ENV}"
        sendMessage-out-0:
          destination: "dwf-connector-${DIGIWF_ENV}"
      kafka:
        binder:
          configuration:
            security:
              protocol: ${KAFKA_SECURITY_PROTOCOL:PLAINTEXT}
          producerProperties:
            value:
              serializer: org.springframework.kafka.support.serializer.JsonSerializer
            key:
              serializer: org.springframework.kafka.support.serializer.JsonSerializer
          consumerProperties:
            auto:
              offset:
                reset: latest
            key:
              deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
            value:
              deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
          brokers: ${KAFKA_BOOTSTRAP_SERVER:localhost}:${KAFKA_BOOTSTRAP_SERVER_PORT:29092}
  kafka:
    consumer:
      properties:
        spring:
          json:
            trusted:
              packages: '*'
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
digiwf:
  integration:
    dms:
      fabasoft:
        businessapp: digiwf
        username: ${FABASOFT_DMS_USERNAME}
        password: ${FABASOFT_DMS_PASSWORD}
        address: "${FABASOFT_DMS_HOST:http://localhost}:${FABASOFT_DMS_PORT:8191}/services/dms"
        enable-MTOM: ${FABASOFT_ENABLE_MTOM:true}
  security:
    # client-id and client-secret are required for feign client authentication
    client-id: ${SSO_TASK_CLIENT_ID}
    client-secret: ${SSO_TASK_CLIENT_SECRET}

io:
  muenchendigital:
    digiwf:
      s3:
        client:
          document-storage-url: "${DOCUMENT_STORAGE_HOST:http://localhost}:${DOCUMENT_STORAGE_PORT:8080}"
      message:
        incidentDestination: "dwf-connector-incident-${DIGIWF_ENV}"
        bpmnErrorDestination: "dwf-connector-bpmnerror-${DIGIWF_ENV}"
        correlateMessageDestination: "dwf-connector-${DIGIWF_ENV}"
        typeMappings:
          createProcedure: "createProcedureMessageProcessor"
          createDocument: "createDocumentMessageProcessor"
          updateDocument: "updateDocumentMessageProcessor"
          depositObject: "depositObjectMessageProcessor"
          cancelObject: "cancelObjectMessageProcessor"

de:
  muenchen:
    oss:
      digiwf:
        dms:
          supportedExtensions:
            pdf: "application/pdf"
            txt: "text/plain"
            png: "image/png"
            jpg: "image/jpeg"
            docx: "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
            xlsx: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
            pptx: "application/vnd.openxmlformats-officedocument.presentationml.presentation"
            vsdx: "application/vnd.visio2013"
            mpp: "application/vnd.ms-project"
            odf: "application/vnd.oasis.opendocument.formula"
            odp: "application/vnd.oasis.opendocument.presentation"
            ods: "application/vnd.oasis.opendocument.spreadsheet"
            odt: "application/vnd.oasis.opendocument.text"
