spring:
  cloud:
    gateway:
      actuator:
        verbose:
          enabled: false
      routes:
        - id: sso
          uri: ${SSO_BASE_URL}
          predicates:
            - Path=/api/sso/userinfo
          filters:
            - RewritePath=/api/sso/userinfo, /realms/${SSO_REALM}/protocol/openid-connect/userinfo

        - id: backend
          uri: http://${ENGINE_SERVER_HOST:localhost}:${ENGINE_SERVER_PORT}/
          predicates:
            - Path=/api/digitalwf-backend-service/rest/**
          filters:
            - RewritePath=/api/digitalwf-backend-service/(?<urlsegments>.*), /$\{urlsegments}
            - RemoveResponseHeader=WWW-Authenticate

        - id: frontend
          uri: http://localhost:8081/
          predicates:
            - Path=/**

      default-filters:
        - TokenRelay=

  mvc:
    log-request-details: on
