spring:
  cloud:
    gateway:
      routes:
        - id: backend-dockerized
          uri: http://digiwf-engine:${ENGINE_SERVER_PORT}/
          predicates:
            - Path=/api/digitalwf-backend-service/**
          filters:
            - RewritePath=/api/digitalwf-backend-service/(?<urlsegments>.*), /$\{urlsegments}
            - RemoveResponseHeader=WWW-Authenticate

        - id: backend-cockpit
          uri: http://digiwf-engine:${ENGINE_SERVER_PORT}
          predicates:
            - Path=/camunda/**

        - id: tasklist-dockerized
          uri: http://digiwf-tasklist-service:${TASKSERVICE_SERVER_PORT}/
          predicates:
            - Path=/api/digitalwf-tasklist-service/rest/**
          filters:
            - RewritePath=/api/digitalwf-tasklist-service/(?<urlsegments>.*), /$\{urlsegments}
            - RemoveResponseHeader=WWW-Authenticate

        - id: backend-cockpit
          uri: http://digiwf-engine:${ENGINE_SERVER_PORT}
          predicates:
            - Path=/camunda/**

        # integrations
        - id: signing-integration
          uri: http://digiwf-signing:${SIGNING_INTEGRATION_PORT}/
          predicates:
            - Path=/api/integration/**
          filters:
            - RewritePath=/api/integration/(?<urlsegments>.*), /$\{urlsegments}
            - RemoveResponseHeader=WWW-Authenticate

        - id: frontend-dockerized
          uri: http://digiwf-tasklist:8080/
          predicates:
            - Path=/**


