spring:
  cloud:
    stream:
      bindings:
        functionRouter-in-0:
          group: "dwf-cosys-service"
          destination: "dwf-cosys-${DIGIWF_ENV}"
        sendMessage-out-0:
          destination: "dwf-connector-${DIGIWF_ENV}"

io:
  muenchendigital:
    digiwf:
      message:
        incidentDestination: "dwf-connector-incident-${DIGIWF_ENV}"
        bpmnErrorDestination: "dwf-connector-bpmnerror-${DIGIWF_ENV}"
        correlateMessageDestination: "dwf-connector-${DIGIWF_ENV}"
        deadLetterQueueDestination: "dwf-connector-incident-${DIGIWF_ENV}"
