spring:
  cloud:
    stream:
      kafka:
        binder:
          consumerProperties:
            auto.offset.reset: latest
          configuration:
            security:
              #protocol: SSL
