server:
  port: ${COSYS_INTEGRATION_SERVER_PORT:8080}

digiwf:
  security:
    client-id: ${SSO_COSYS_CLIENT_ID}
    client-secret: ${SSO_COSYS_CLIENT_SECRET}

io:
  muenchendigital:
    digiwf:
      cosys:
        url: ${COSYS_URL}
        messageTopic: "dwf-connector-${DIGIWF_ENV}"
        incidentTopic: "dwf-connector-incident-${DIGIWF_ENV}"
        merge:
          datafile: /root/multi
          inputLanguage: Deutsch
          outputLanguage: Deutsch
          keepFields: unresolved-ref
        webform-url: ${COSYS_WEBFORM_URL}
      s3:
        client:
          documentStorageUrl: '${DIGIWF_S3_HTTPAPI:http://localhost:8086}'

spring:
  application:
    name: @project.artifactId@
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: https://sso.cib.de/auth/realms/cosys
            user-info-uri: https://sso.cib.de/auth/realms/cosys/protocol/openid-connect/userinfo
            jwk-set-uri: https://sso.cib.de/auth/realms/cosys/protocol/openid-connect/certs
        registration:
          cosys:
            provider: keycloak
            authorization-grant-type: client_credentials
            client-id: ${digiwf.security.client-id}
            client-secret: ${digiwf.security.client-secret}
            scope: openid  # needed for userInfo endpoint