name: build services

on:
  push:
    branches:
      - '**'

jobs:
  compliance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Advance Security Compliance Action
        uses: GeekMasher/advanced-security-compliance@v1.6.2
        with:
          policy: GeekMasher/security-queries
          policy-path: policies/default.yml
          token: ${{ secrets.ACCESS_TOKEN }}
          argvs: '--disable-dependabot --disable-secret-scanning --disable-code-scanning'

  build-maven:
    needs: compliance
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: camunda-bpm-nexus-ee
          server-username: CAMUNDA_USER_REF
          server-password: CAMUNDA_TOKEN_REF

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
        env:
          CAMUNDA_USER_REF: ${{ secrets.CAMUNDA_USER }}
          CAMUNDA_TOKEN_REF: ${{ secrets.CAMUNDA_USER_PASSWORD }}

