name: build apps

on:
  push:
    paths:
      - 'digiwf-apps/**'
  pull_request:

jobs:
  build:
    uses: ./.github/workflows/workflow-build-apps.yaml
    with:
      publish-packages: false
      build-images: ${{ github.ref_name == 'dev' }}
      release-version: 'dev'
    secrets: inherit
