name: build services

on: [push, pull_request]

jobs:
  build-maven:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: camunda-bpm-nexus-ee
          server-username: CAMUNDA_USER_REF
          server-password: CAMUNDA_TOKEN_REF

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots --no-transfer-progress verify
        env:
          CAMUNDA_USER_REF: ${{ secrets.CAMUNDA_USER }}
          CAMUNDA_TOKEN_REF: ${{ secrets.CAMUNDA_USER_PASSWORD }}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          working-directory: ./digiwf-coverage/target/coverage/
          directory: ./digiwf-coverage/target/coverage/
          fail_ci_if_error: true
          files: ./jacoco.xml
          flags: unittests
          name: digiwf-core
          path_to_write_report: codecov_report.txt
          verbose: true