name: build apps

on:
  push:
    branches:
      - '**'
    paths:
      - 'digiwf-apps/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./digiwf-apps
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: "./digiwf-apps/package-lock.json"
      - run: npm run init
      - run: npm run test
      - run: npm run build
