name: build docs

on:
  push:
    paths:
      - 'docs/**'
  pull_request:

env:
  NODE_OPTIONS: '--openssl-legacy-provider'

jobs:
  build:
    uses: ./.github/workflows/workflow-build-docs.yaml
    with:
      publish: false
    secrets: inherit
