name: build apps

# For now we test the frontend by just building it, in the future tests should be run here

on:
  push:
    branches:
      - '**'
    paths:
      - 'digiwf-apps/**'
  pull_request:
    branches:
      - 'dev'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./digiwf-apps
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: "./digiwf-apps/package-lock.json"
      - run: npm run init
      - run: npm run build
