name: check license compliance

on:
  pull_request:
    branches:
      - dev

jobs:
  compliance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # Policy as Code
      - name: Advance Security Policy as Code
        uses: advanced-security/policy-as-code@v2.3
        with:
          policy: GeekMasher/security-queries
          policy-path: policies/default.yml
          argvs: '--disable-dependabot --disable-secret-scanning --disable-code-scanning'
