name: check license compliance

on:
  pull_request:
    branches:
      - dev

jobs:
  compliance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # Compliance
      - name: Advance Security Policy as Code
        uses: advanced-security/policy-as-code@v2.5.0
        with:
          policy: it-at-m/policy-as-code
          policy-path: default.yaml
