name: check license compliance

on: [ push, pull_request ]

jobs:
  compliance:
    runs-on: ubuntu-latest

  steps:
    - name: Checkout code
      uses: actions/checkout@v3
    # Policy as Code
    - name: Advance Security Policy as Code
      uses: advanced-security/policy-as-code@v2.1
      with:
        policy: GeekMasher/security-queries
        policy-path: policies/default.yml
        # GitHub Personal Access Token to access the GitHub API.
        # Secret Scanning and Dependabot do not allow their resources to be
        #  exposed to Actions so this might need to be set using a token that has
        #  the ability to access the resources
        token: ${{ secrets.ACCESS_TOKEN }}
        argvs: '--disable-dependabot --disable-secret-scanning --disable-code-scanning'
