name: release apps

# Run workflow on commits to the `main` branch
on:
  workflow_dispatch:
    inputs:
      snapshot-build:
        description: 'Snapshot build (y/n)?'
        required: true
        default: 'y'
  push:
    tags:
      - 'apps_*.*.*'

jobs:
  release-apps:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./digiwf-apps
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
          cache-dependency-path: "./digiwf-apps/package-lock.json"
      - run: npm install && lerna bootstrap --ci
      - run: npm run build
      - run: lerna publish from-package --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_KEY }}

      - name: Set Release version env variable
        if: ${startsWith(github.ref, 'refs/tags/') || github.event.inputs.snapshot-run == 'n'}
        run: |
          echo "RELEASE_VERSION=$(grep -m1 version lerna.json | awk -F: '{ print $2 }' | sed 's/[", ]//g')" >> $GITHUB_ENV

      - name: Set Snapshot Release version env variable
        if: github.event.inputs.test-run == 'y'
        run: |
          echo "RELEASE_VERSION=$(grep -m1 version lerna.json | awk -F: '{ print $2 }' | sed 's/[", ]//g')-SNAPSHOT" >> $GITHUB_ENV

      - name: Build and push tasklist
        uses: docker/build-push-action@v2
        with:
          context: ./digiwf-apps/packages/apps/digiwf-tasklist
          push: true
          tags: itatm/digiwf-tasklist:${{ env.RELEASE_VERSION }}