name: release services

# Run workflow on commits to the `main` branch
on:
  push:
    tags:
      - 'apps_*.*.*'

jobs:
  release-apps:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./digiwf-apps
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
          cache-dependency-path: "./digiwf-apps/package-lock.json"
      - run: npm install && lerna bootstrap --ci
      - run: npm run build
      - run: lerna publish from-package --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
