name: Require Checklist

on:
  pull_request:
    types: [opened, edited, synchronize, ready_for_review]

jobs:
  checklist-check:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' && github.event.pull_request.draft == false }}
    steps:
      - uses: mheap/require-checklist-action@v2
        with:
          requireChecklist: true
