name: snapshot release services

# Run workflow on commits to the `main` branch
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./digiwf-apps
    steps:
      - name: Build Apps
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: "./digiwf-apps/package-lock.json"
      - run: npm run init
      - run: npm run build

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_KEY }}

      - name: Build and push tasklist
        uses: docker/build-push-action@v2
        with:
          context: ./packages/apps/digiwf-tasklist
          push: true
          tags: itatm/digiwf-tasklist:${{ env.RELEASE_VERSION }}